version: "3.8"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next_perf
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
